### ISSUE TITLE
Documentation available on pkg.go.dev

### ISSUE THREAD

**Issue by julieqiu** [sams96/rgeo#10]
Hello!

I work on pkg.go.dev, and  we received a bug asking the the following:
```
My projects (github.com/sams96/rgeo) documentation hasn't updated for the last 2 releases.
```
I wanted to let you know that the latest versions of your project should be available on pkg.go.dev. You can see all of the available versions here:

https://pkg.go.dev/mod/github.com/sams96/rgeo?tab=versions

We monitor the [Go Module Index](https://index.golang.org) regularly for new packages to add to pkg.go.dev. If you don’t see a package on pkg.go.dev, you can add it by:

1. Making a request to [proxy.golang.org](https://proxy.golang.org) for the module version: 
- For example, `https://proxy.golang.org/github.com/sams96/rgeo/@v/v1.0.0.info`

2. Downloading the package via the go command:
- For example, `GO111MODULE=on go get <package> `

Documentation is generated based on Go source code downloaded from the `proxy.golang.org/<module>@<version>.zip`. New packages and modules are added to pkg.go.dev every few minutes.

Hope this helps!

**Comment by sams96** [comment]
Hi @julieqiu, thanks for the quick response. If you check [https://pkg.go.dev/github.com/sams96/rgeo](https://pkg.go.dev/github.com/sams96/rgeo) it claims that v0.0.4 is the latest version and I can't get the docs for v0.0.5 or v1.0.0. I have used go get to ping the server, which I guess is why it has the module page but it hasn't updated for the package.

**Comment by julieqiu** [comment]
Hi @sams96 - the reason is because in both v0.0.5 and v1.0.0 of github.com/sams96/rgeo, there were files that exceed our limit. The issue seems to be coming from: 

- https://github.com/sams96/rgeo/blob/v1.0.0/Provinces10.go
- https://github.com/sams96/rgeo/blob/v1.0.0/Cities10.go
- https://github.com/sams96/rgeo/blob/v0.0.5/Provinces10.go

**Comment by sams96** [comment]
@julieqiu I was thinking that must be it, what is the limit? Is there any way to tell pkg.go.dev to just ignore those files and still parse everything else?

**Comment by sams96** [comment]
Hi @julieqiu, I released a new version yesterday in which I compressed the large data files and the docs are working again. I'm still curious as to what that limit is though?

**Comment by julieqiu** [comment]
Great! It's 30MB.

**Comment by sams96** [comment]
Thanks
