### ISSUE TITLE
Minimize RAM usage

### ISSUE THREAD

**Issue by guillermo-st** [sams96/rgeo#24]
**EDIT: Just noticed the Countries110 dataset has a pretty low ram consumption, I think I will settle for that :). How different is it from Countries10?**

Hi! I'm currently trying to use rgeo for a college assignment, which asks me to set up a social media server that supports reverse geolocation. I'm using a free hosting solution (fly.io) and because of that I need to minimize RAM usage, otherwise I will need to pay for the host :(

Is only loading the Countries10 dataset the best I can do? (doing that consumes about ~250MB of ram idling) .Including provinces and cities ramps up the usage to 10GB of ram according to my IDE profiler.

Thanks for the help and sorry for the very unrelated issue

**Comment by sams96** [comment]
As per the readme:
> `Countries110` - Just country information, smallest and lowest detail of the included datasets.

If you want to further reduce RAM usage, I would suggest investigating some older versions, I think trying at f231340c51 might help.
