### ISSUE TITLE
tzdata?

### ISSUE THREAD

**Issue by notrobpike** [sams96/rgeo#32]
I want to get US and Canada regions like east/west/midwest. The countries databases are too coarse and the cities&provinces databases are too fine. Is it possible to include the natural earth timezone database and from there I can get a nice granularity that I'm looking for? If not I can just build a hash of the subregions from the cities database I guess.

https://www.naturalearthdata.com/downloads/10m-cultural-vectors/timezones/

nearly 2MB, which isn't too bad. I'm doubtful that the TZ database contains details like cities that don't conform to daylight savings, so it would be misleading that way, but for my purpose it would be great.

**Comment by sams96** [comment]
I'm not looking to add more datasets to this project, and am rather looking to go in the opposite direction. You can use any dataset of your choosing by just running it through the `datagen` script and embedding it as is done in `embed.go`, then use it as you would any other. This appears to be an area of documentation that is lacking.

There is also the issue that the field you need from your data isn't present in this package, which isn't really solvable purely on your end, which is something I would like to solve but for the time being you can create a PR to add the field you need.
